name: sb
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python>=3.11.0,<3.12
  - setuptools==69.5.1
  - easydict==1.9
  - hydra-core==1.3.2
  - flask==2.3.3
  - numpy==1.26.4
  - pandas==2.2.2
  - pip==24.0
  - pybullet==3.25
  - pysolr==3.9.0
  - scipy==1.13.0
  - pytorch==2.1.0
  - pytorch-cuda=12.1
  - torchvision==0.16.0 
  - flask-restx==1.3.0
  - Werkzeug==2.3.7
  - einops==0.7.0
  - pip:
    # - setuptools==69.5.1
    - pytorch-fast-transformers==0.4.0
    - clip
    - transformers==4.40.0
    - shapely==2.0.2
    - openai==1.52.0
    - python-dotenv==1.0.1
    - imageio==2.34.1
    - trimesh==4.3.1
    - clean-fid==0.1.35
    - nltk==3.8.1
    - tensorboard==2.16.2
    - diffusers==0.27.2
    - pygltflib==1.16.2
    - open_clip_torch==2.24.0
    - pyvis==0.3.2
    - git+https://github.com/openai/shap-e.git
    - trimesh
    - python-fcl
    - langchain==0.2.16
    - langchain_community==0.2.17
    - langchain_openai==0.1.25
    - compress_json==1.1.0
    - compress_pickle==2.1.0
    - sentence_transformers==3.1.0
    - colorama==0.4.6
    - moviepy==1.0.3
    - editdistance==0.8.1
    - rtree==1.3.0
    - cvxpy==1.5.3
    - procthor==0.0.1.dev2
    - huggingface-hub==0.24.7