name: sb
channels:
  - pytorch
  - conda-forge
dependencies:
  - easydict
  - hydra-core
  - flask==2.3.3
  - numpy
  - pip
  - pybullet
  - pysolr
  - scipy
  - pytorch
  - torchvision
  - flask-restx
  - Werkzeug==2.3.7
  - einops
  - pip:
    - pytorch-fast-transformers
    - clip==0.2.0
    - flask-restx
    - transformers
    - shapely==2.0.2
