data:
    dataset_type: "cached_threedfront"
    encoding_type: "cached_desc_sgdiffusion"
    augmentations: ["fixed_rotation"]
    dataset_directory: "dataset/InstructScene/threed_front_livingroom"
    annotation_file: "configs/livingroom_threed_front_splits.csv"
    path_to_invalid_scene_ids: "configs/invalid_threed_front_rooms.txt"
    path_to_invalid_bbox_jids: "configs/black_list.txt"
    path_to_floor_plan_textures: "configs/floor_plan_texture_images"
    path_to_pickled_3d_futute_models: "dataset/InstructScene/threed_future_model_livingroom.pkl"
    filter_fn: "threed_front_livingroom"
    train_stats: "dataset_stats.txt"
    room_layout_size: "64,64"
    max_length: 21
    classes: [armchair.n.01, bookcase.n.01, cabinet.n.01, ceiling_lamp.n.01, chaise_longue.n.01, chair.n.01, coffee_table.n.01, console_table.n.01, table.n.02, desk.n.01, chair.n.01, dining_table.n.01, l-shaped_couch.n.01, sofa.n.01, chair.n.01, chair.n.01, sofa.n.01, pendant_lamp.n.01, end_table.n.01, shelf.n.01, stool.n.01, tv_stand.n.01, wardrobe.n.01, wine_rack.n.01, start, end]
    raw_classes: ["armchair", "bookcase", "cabinet", "ceiling lamp", "chaise longue sofa", "chinese chair", "coffee table", "console table", "corner/side table", "desk", "dining chair", "dining table", "l-shaped sofa", "lazy sofa", "lounge chair", "loveseat sofa", "multi-seat sofa", "pendant lamp", "round end table", "shelf", "stool", "tv stand", "wardrobe", "wine cabinet"]
    predicate_types: ["above", "left of", "in front of", "closely left of", "closely in front of", "below", "right of", "behind", "closely right of", "closely behind"]
    reverse_predicates:
        "above": "below"
        "below": "above"
        "in front of": "behind"
        "behind": "in front of"
        "left of": "right of"
        "right of": "left of"
        "closely in front of": "closely behind"
        "closely behind": "closely in front of"
        "closely left of": "closely right of"
        "closely right of": "closely left of"

network:
    name: "vq_objfeat_sg_gtf"
    text_encoder: "openai/clip-vit-base-patch32"
    ckpt_dir: ".data/models/instructscene/livingroom/text_to_sg"
    ckpt_epoch: null
    cfg_scale: 1.

training:
    splits: ["train", "val"]
    epochs: 2000
    steps_per_epoch: 500
    batch_size: 128
    save_frequency: 10
    log_frequency: 1
    optimizer:
        name: "adamw"
        lr: 0.0001
        weight_decay: 0.02
    loss_weights:
        vb_x: 1.
        vb_e: 1.
    ema:
        use_ema: true
        max_decay: 0.9999
        min_decay: 0.
        update_after_step: 0
        use_warmup: true
        inv_gamma: 1.
        power: 0.75

validation:
    splits: ["test"]
    batch_size: 256
    frequency: 1
