base_dir: ???

scene_builder:
  arch_db:
    path: null
  scene_db:
    path: "${base_dir}/stk/scenestate"
  model_db:
    source: "fpModel"
    mesh_dir: "${base_dir}/object-noq"
    collision_mesh_dir: "${base_dir}/convex/furniture-coacd-tp2"
    defaults:
      up: [0, 1, 0]
      front: [0, 0, 1]
  solr_url: ???

defaults:
  - _self_
  - generator@atiss: atiss

hydra:
  # disable changing of cwd as it interferes with flask auto-restart
  run:
    dir: .
  # output files creation
  output_subdir: null