base_dir: "/datasets/internal/hssd"
base_url: ???  # base url for scene builder API requests
structured3d_path: ???  # base path to structured3d architecture files

scene_builder:
  arch_db:
    metadata: .data/datasets/structured3d/structured3d.rooms.csv
    path: "${base_url}/${structured3d_path}/arch/{scene_id}.arch.json"
  scene_db:
    path: "${base_dir}/fpsb/scenes/cluttered/scenestate"
  model_db:
    source: "fpModel"  # this is ONLY the source for retrieving models from solr
    mesh_dir: "${base_dir}/hssd-hab/objects"
    collision_mesh_dir: "${base_dir}/hssd-hab/objects"
    generation:  # TODO: make a separate configuration for this
      output_dir: ???  # directory to output generated models
      metadata_file: ???  # path to csv file at which to maintain metadata of generated models
      guidance_scale: 15.0
      batch_size: 1
    retrieval:
      embedding_field: f_openshape_p_1280
      top_k: 10
    size_threshold: 0.25
    defaults:
      up: [0, 1, 0]
      front: [0, 0, 1]
    threed_future_db:
      datasets:
        bedroom: .data/datasets/threed_future/threed_future_model_bedroom.json
        diningroom: .data/datasets/threed_future/threed_future_model_diningroom.json
        livingroom: .data/datasets/threed_future/threed_future_model_livingroom.json
      use_object_class: true
      use_object_size: false
    default_object_gen_method: "retrieve"
    default_object_retrieve_type: "category"
    text_encoder: "ViT-bigG-14"
  solr_url: ???  # url for solr database API queries

defaults:
  - _self_
  - layout_generator@layout: layout_mapping
  - scene_parser@parser: parser_mapping
  - arch_generator@arch: arch_generator_mapping

hydra:
  # disable changing of cwd as it interferes with flask auto-restart
  run:
    dir: .
  # output files creation
  output_subdir: null

data: ".data/evaluation/test_prompts_example.csv"
# output_dir: "/project/3dlg-hcvc/text2scene/www/comparison"
output_dir: ".data/evaluation/generated_scenes"
output_prompt_file: "test_prompts.json"
semantic_index: ".data/evaluation/semantic_color_index.csv"
skip_existing_stk: false
skip_existing_render: false
use_semantic_render: false

methods:
  - name: ATISS
    params:
      sceneInference.parserModel: RoomTypeLLM
      sceneInference.layoutModel: ATISS
  - name: DiffuScene
    params:
      sceneInference.parserModel: RoomTypeLLM
      sceneInference.layoutModel: DiffuScene
      sceneInference.passTextToLayout: "True"
  - name: InstructScene
    params:
      sceneInference.parserModel: InstructScene
      sceneInference.layoutModel: InstructScene
  - name: LLM_InstructScene
    params:
      sceneInference.parserModel: LLM
      sceneInference.layoutModel: InstructScene