data:
    dataset_type: "cached_threedfront"
    encoding_type: "cached_graph_sincos_angle_sg2sc"
    augmentations: ["fixed_rotation"]
    dataset_directory: "dataset/InstructScene/threed_front_bedroom"
    annotation_file: "configs/bedroom_threed_front_splits.csv"
    path_to_invalid_scene_ids: "configs/invalid_threed_front_rooms.txt"
    path_to_invalid_bbox_jids: "configs/black_list.txt"
    path_to_floor_plan_textures: "configs/floor_plan_texture_images"
    path_to_pickled_3d_futute_models: "dataset/InstructScene/threed_future_model_bedroom.pkl"
    filter_fn: "threed_front_bedroom"
    train_stats: "dataset_stats.txt"
    room_layout_size: "64,64"
    room_dims: [6.2, 6.2]  # in meters; [x_max - x_min, y_max - y_min]
    max_length: 12
    classes: [armchair.n.01, bookcase.n.01, cabinet.n.01, ceiling_lamp.n.01, chair.n.01, cabinet.n.01, coffee_table.n.01, desk.n.01, double_bed.n.01, chair.n.01, dressing_table.n.01, bunk_bed.n.01, nightstand.n.01, pendant_lamp.n.01, shelf.n.01, single_bed.n.01, sofa.n.01, stool.n.01, table.n.02, tv_stand.n.01, wardrobe.n.01, start, end]
    raw_classes: ["armchair", "bookcase", "cabinet", "ceiling lamp", "chair", "children cabinet", "coffee table", "desk", "double bed", "dressing chair", "dressing table", "kids bed", "nightstand", "pendant lamp", "shelf", "kids bed", "sofa", "stool", "table", "tv stand", "wardrobe"]
    predicate_types: ["above", "left of", "in front of", "closely left of", "closely in front of", "below", "right of", "behind", "closely right of", "closely behind"]
    reverse_predicates:
        "above": "below"
        "below": "above"
        "in front of": "behind"
        "behind": "in front of"
        "left of": "right of"
        "right of": "left of"
        "closely in front of": "closely behind"
        "closely behind": "closely in front of"
        "closely left of": "closely right of"
        "closely right of": "closely left of"
    bounds: {sizes: [[0.03998288, 0.02000002, 0.012772], [2.8682, 1.770065, 1.698315]], translations: [[-2.7625005, 0.045, -2.75275], [2.77844175, 3.6248396, 2.81854277]], angles: [-3.14159265, 3.14159265]}
    up_axis: "y"
export_room_mask: false

network:
    name: "vq_objfeat_sg_gtf"
    text_encoder: "ViT-bigG-14"
    ckpt_dir: .data/models/instructscene/bedroom/sg_to_sc
    ckpt_epoch: null
    objfeat_bounds: .data/models/instructscene/objfeat_bounds.pkl
    vqvae_checkpoint: .data/models/instructscene/threedfront_objfeat_vqvae_epoch_01999.pth
    cfg_scale: 1.
    room_mask_condition: false  # currently ignored

training:
    splits: ["train", "val"]
    epochs: 2000
    steps_per_epoch: 500
    batch_size: 128
    save_frequency: 10
    log_frequency: 1
    optimizer:
        name: "adamw"
        lr: 0.0001
        weight_decay: 0.02
    loss_weights:
        pos_mse: 1.
        size_mse: 1.
        angle_mse: 1.
    ema:
        use_ema: true
        max_decay: 0.9999
        min_decay: 0.
        update_after_step: 0
        use_warmup: true
        inv_gamma: 1.
        power: 0.75

validation:
    splits: ["test"]
    batch_size: 256
    frequency: 1

device: cuda
